Repository AY2021S1-CS2103T-W12-2/tp, pull requests merged in 2020-11, with the labels that each got.

#176 add participationBelow and attendanceBelow commands
  src/main/java/seedu/address/logic/commands/AttendanceBelowCommand.java
  src/main/java/seedu/address/logic/commands/ParticipationBelowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceBelowCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ParticipationBelowCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/AttendanceBelowSpecifiedScorePredicate.java
  src/main/java/seedu/address/model/person/ParticipationBelowSpecifiedScorePredicate.java
Labels: priority.High

#180 solve bugs involving CommandResult boolean fields
  src/main/java/seedu/address/logic/commands/AttendanceBelowCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListTutorialGroupCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Trackr.java
Labels: priority.High, type.Task

#181 clear command brings back user to module view
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, type.Bug

#182 Small fixes
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModuleContainsKeywordsPredicate.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Task

#188 Fixes bugs relating to Tutorial Group identified during PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/FindTutorialGroupCommandParser.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialContainsKeywordsPredicate.java
Labels: priority.Medium, type.Bug

#189 Add storage testcases
  src/main/java/seedu/address/model/student/Attendance.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedWeekNumber.java
  src/test/data/JsonModuleListStorageTest/invalidAndValidModuleModuleList.json
  src/test/data/JsonModuleListStorageTest/invalidModuleModuleList.json
  src/test/data/JsonModuleListStorageTest/notJsonFormatModuleList.json
  src/test/data/JsonSerializableModuleListTest/duplicateModuleModuleList.json
  src/test/data/JsonSerializableModuleListTest/invalidModuleModuleList.json
  src/test/data/JsonSerializableModuleListTest/typicalModulesModuleList.json
  src/test/java/seedu/address/model/student/AttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonModuleListStorageTest.java
Labels: priority.High, type.Task

#191 Fix ug issues
  docs/UserGuide.md
Labels: priority.High

#192 fix find substring issue
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
Labels: type.Bug

#194 Add TrackrParser tests
  src/main/java/seedu/address/logic/parser/ParticipationBelowCommandParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/parser/TrackrParserTest.java
  src/test/java/seedu/address/testutil/AttendanceBuilder.java
  src/test/java/seedu/address/testutil/AttendanceUtil.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TutorialGroupUtil.java
Labels: priority.High

#201 fix edit module command bug
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Trackr.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleId.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTutorialGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/TrackrParserTest.java
Labels: type.Bug

#202 add tests for participationBelow and attendanceBelow
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceBelowCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/ParticipationBelowCommand.java
  src/main/java/seedu/address/model/module/ModuleId.java
  src/test/java/seedu/address/logic/commands/AttendanceBelowCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/ParticipationBelowCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModulesPopulatedWithTutorialGroups.java
Labels: type.Task

#203 Updates EditTutorialGroupCommand to work with at least one argument
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/EditTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialGroup.java
  src/test/java/seedu/address/logic/commands/AddTutorialGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTutorialGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTutorialGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTutorialGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTutorialGroupCommandParserTest.java
Labels: priority.Medium, type.Task

#205 change display messages
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/model/module/ModuleId.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialGroupId.java
Labels: priority.Medium

#207 add more tests
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/Trackr.java
  src/main/java/seedu/address/model/tutorialgroup/DayOfWeek.java
  src/main/java/seedu/address/model/tutorialgroup/TimeOfDay.java
  src/test/java/seedu/address/logic/commands/AttendanceBelowCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ParticipationBelowCommandTest.java
  src/test/java/seedu/address/model/student/AttendanceBelowSpecifiedScorePredicateTest.java
  src/test/java/seedu/address/model/student/ModuleContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/student/ModuleIdTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/ParticipationBelowSpecifiedScorePredicateTest.java
  src/test/java/seedu/address/model/student/UniqueModuleListTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
Labels: type.Task

#209 Fix statusbar footer message
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: severity.High, type.Bug

#210 fix tests and checkstyle
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AttendanceBelowCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/ParticipationBelowCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModulesPopulatedWithTutorialGroups.java
Labels: priority.Medium

#212 Add Tests for Attendance, Participation, and Views
  src/main/java/seedu/address/logic/commands/PreviousViewCommand.java
  src/main/java/seedu/address/model/student/Attendance.java
  src/test/java/seedu/address/logic/commands/AddAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/EditParticipationCommandTest.java
  src/test/java/seedu/address/logic/commands/PreviousViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTutorialGroupCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalTutorialGroups.java
Labels: priority.High

#211 fix editMod bug
  docs/UserGuide.md
  docs/images/AddModuleCommand.png
  docs/images/ClearCommand.png
  docs/images/DeleteModuleCommand.png
  docs/images/EditMod.png
  docs/images/FindModuleCommand.png
  docs/images/HelpCommand.png
  docs/images/ListModuleCommand.png
  docs/team/juandavinlie.md
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
Labels: type.Bug

#215 Update UG Navigation Features
  docs/UserGuide.md
Labels: priority.High

#217 fix editTG bug
  docs/DeveloperGuide.md
  docs/diagrams/AddModSequenceDiagram.puml
  docs/diagrams/EditStudentSequenceDiagram.puml
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Trackr.java
Labels: type.Bug

#218 add sequence diagrams for all features in DG
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/DeleteModuleSequenceDiagram.puml
  docs/diagrams/EditModuleSequenceDiagram.puml
  docs/diagrams/ExitCommandSequenceDiagram.puml
  docs/diagrams/FindModuleSequenceDiagram.puml
  docs/diagrams/ListModuleCommandSequenceDiagram.puml
  docs/diagrams/ViewTutorialGroupCommandSequenceDiagram.puml
  docs/images/AddModSequenceDiagram.png
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/DeleteModuleSequenceDiagram.png
  docs/images/EditModuleSequenceDiagram.png
  docs/images/ExitCommandSequenceDiagram.png
  docs/images/FindModuleSequenceDiagram.png
  docs/images/ListModuleCommandSequenceDiagram.png
  docs/images/ViewTutorialGroupCommandSequenceDiagram.png
  docs/team/juandavinlie.md
Labels: priority.High

#222 add instruction for manual testing and glossary for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#223 update findmodulesequencediagram.puml and dg
  docs/DeveloperGuide.md
  docs/diagrams/FindModuleSequenceDiagram.puml
  docs/images/FindModuleSequenceDiagram.png
Labels: priority.High

#227 add javadoc comments
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/Trackr.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleId.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
Labels: priority.Medium

#233 rearranged UG for TG features
  docs/UserGuide.md
Labels: priority.Medium

#238 Fix command error message bugs
  src/main/java/seedu/address/logic/commands/AddAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceBelowCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditParticipationCommand.java
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ParticipationBelowCommand.java
Labels: severity.Medium, type.Bug

#241 fix inconsistencies in UG
  docs/UserGuide.md
Labels: priority.High

#243 Improves Testing for classes related to Tutorial Group
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/model/tutorialgroup/DayOfWeek.java
  src/main/java/seedu/address/model/tutorialgroup/TimeOfDay.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialGroup.java
  src/test/java/seedu/address/logic/commands/ListTutorialGroupsCommandTest.java
  src/test/java/seedu/address/model/student/DayOfWeekTest.java
  src/test/java/seedu/address/model/student/TimeOfDayTest.java
  src/test/java/seedu/address/model/student/TutorialContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/TutorialGroupIdTest.java
  src/test/java/seedu/address/model/student/TutorialGroupTest.java
  src/test/java/seedu/address/model/student/UniqueModuleListTest.java
  src/test/java/seedu/address/model/student/UniqueTutorialGroupListTest.java
  src/test/java/seedu/address/testutil/TutorialGroupBuilder.java
Labels: priority.Medium

#255 beautify status message
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/ViewTutorialGroupCommand.java
Labels: priority.Low
