Repository AY2021S1-CS2103T-W12-2/tp, pull requests merged in 2020-10, with the labels that each got.

#33 Add tutorial group class
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/TutorialGroup.java
  src/main/java/seedu/address/model/person/Student.java
Labels: priority.High, type.Task

#34 Add module class
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Student.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/ModuleTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: priority.High, type.Task

#38 Add Task and TaskList class
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Task.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/TutorialGroup.java
  src/main/java/seedu/address/model/person/Module.java
Labels: priority.High, type.Task

#41 Add cards and listPanels for Module, Student and Task
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: priority.High, type.Task

#45 Add UniqueModuleList
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/UniqueModuleList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/person/exceptions/ModuleNotFoundException.java
  src/test/java/seedu/address/model/person/UniqueModuleListTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task

#48 Add UniqueTutorialGroupList class
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TutorialGroup.java
  src/main/java/seedu/address/model/person/UniqueTutorialGroupList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateTutorialGroupException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#49 Add module parsing
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
Labels: priority.High, type.Task

#50 Add tutorial group parsing
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TutorialGroup.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#59 Showing module
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task

#60 Tutorial groups card and list panel
  src/main/java/seedu/address/ui/TutorialGroupCard.java
  src/main/java/seedu/address/ui/TutorialGroupListPanel.java
  src/main/resources/view/TutorialGroupListCard.fxml
  src/main/resources/view/TutorialGroupListPanel.fxml
Labels: priority.High, type.Task

#91 Change UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#97 Update gui
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/ViewTutorialGroupCommandParser.java
  src/main/java/seedu/address/model/Trackr.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/tutorialgroup/UniqueTutorialGroupList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/java/seedu/address/ui/ViewDisplay.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TrackrTheme.css
  src/main/resources/view/viewDisplay.fxml
Labels: priority.High

#100 add restriction for module features
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exceptions/NotInModuleViewException.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/ui/ModuleCard.java
Labels: priority.High, type.Task

#102 Add Student commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ViewStudentCommand.java
  src/main/java/seedu/address/logic/commands/ViewTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindStudentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task

#107 Fix main checkstyle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/ListTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ViewTutorialGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTutorialGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewTutorialGroupCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Trackr.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialGroup.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/TutorialGroupCard.java
  src/main/java/seedu/address/ui/ViewDisplay.java
Labels: priority.Medium

#112 Update tg commands
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditTutorialGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListTutorialGroupCommand.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StudentStorage.java
Labels: priority.Medium, type.Task

#124 fix checkstyleTest and checkstyleMain
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.High, type.Task

#172 add total students field in tg
  src/main/java/seedu/address/model/person/UniqueStudentList.java
  src/main/java/seedu/address/model/tutorialgroup/TutorialGroup.java
  src/main/java/seedu/address/ui/TutorialGroupCard.java
  src/main/resources/view/TutorialGroupListCard.fxml
Labels: priority.High, type.Task

#173 prevView implemented
  src/main/java/seedu/address/logic/commands/PreviousViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task
